grep "airConditioning" vocabulary/AU/vocabulary.ttl
grep "biocontainmentLevel" vocabulary/AU/vocabulary.ttl
grep "deployedOnPlatform" vocabulary/AU/vocabulary.ttl
grep "deployedSystem" vocabulary/AU/vocabulary.ttl
grep "forBiologicalMaterial" vocabulary/AU/vocabulary.ttl
grep "forBiologicalUnitType" vocabulary/AU/vocabulary.ttl
grep "gasSupply" vocabulary/AU/vocabulary.ttl
grep "hasGrowthFacilityType" vocabulary/AU/vocabulary.ttl
grep "hasMethod" vocabulary/AU/vocabulary.ttl
grep "hasPlatformType" vocabulary/AU/vocabulary.ttl
grep "hasScale" vocabulary/AU/vocabulary.ttl
grep "hasSensorType" vocabulary/AU/vocabulary.ttl
grep "hasTrait" vocabulary/AU/vocabulary.ttl
grep "humidityControl" vocabulary/AU/vocabulary.ttl
grep "lights" vocabulary/AU/vocabulary.ttl
grep "physicalContainmentLevel" vocabulary/AU/vocabulary.ttl
grep "shade" vocabulary/AU/vocabulary.ttl
grep "temperatureRange" vocabulary/AU/vocabulary.ttl
